version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: car_rental_postgres
    environment:
      POSTGRES_DB: car_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - car_rental_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: .
    container_name: car_rental_backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/car_rental
      - WEB3_PROVIDER_URL=http://host.docker.internal:8545
      - CONTRACT_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
    volumes:
      - .:/app
      - ./contract-address.json:/app/contract-address.json
    networks:
      - car_rental_network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:

networks:
  car_rental_network:
    driver: bridge
